/* Sound Advice — sound engine
   ---------------------------------------------------------------
   Every sound except the two music tracks is GENERATED BY CODE.
   Nothing is downloaded, so there is no licensing question, no
   waiting for files, and the sound is byte-identical for every user.

   Why it is generated once and then played as a normal audio track,
   instead of being synthesised live:

   Phones suspend the Web Audio engine as soon as the screen locks or
   you switch apps. Live-synthesised noise would simply stop -- which
   is exactly when a studying person puts their phone down. So we
   render the sound once into a short seamless loop and hand it to the
   ordinary audio player, which phones are happy to keep playing in the
   background (and which shows up in the lock-screen controls).
   --------------------------------------------------------------- */

const SR = 44100;        // samples per second
const RENDER_SECONDS = 24;
const FADE_SECONDS = 2;  // crossfaded away to make the loop seamless

export const SOUNDS = [
  { id: 'silence',   name: 'Silence',      family: 'Silence', desc: 'Just the timer' },

  { id: 'white',     name: 'White noise',  family: 'Noise',   desc: 'Even hiss across all pitches', tone: true },
  { id: 'pink',      name: 'Pink noise',   family: 'Noise',   desc: 'Softer, weighted to lower pitches', tone: true },
  { id: 'brown',     name: 'Brown noise',  family: 'Noise',   desc: 'Deep rumble, gentlest on the ears', tone: true },

  { id: 'rain',      name: 'Rain',         family: 'Nature',  desc: 'Steady rainfall' },
  { id: 'stream',    name: 'Stream',       family: 'Nature',  desc: 'Running water' },
  { id: 'ocean',     name: 'Ocean',        family: 'Nature',  desc: 'Slow waves' },
  { id: 'forest',    name: 'Forest',       family: 'Nature',  desc: 'Wind through leaves' },
  { id: 'fire',      name: 'Fireplace',    family: 'Nature',  desc: 'Crackling fire' },

  { id: 'classical', name: 'Classical',    family: 'Music',   desc: 'Instrumental', file: 'audio/classical.mp3' },
  { id: 'lyrical',   name: 'With lyrics',  family: 'Music',   desc: 'Song with vocals', file: 'audio/lyrical.mp3' }
];

export const soundById = id => SOUNDS.find(s => s.id === id) || SOUNDS[0];
export const FAMILIES = ['Silence', 'Noise', 'Nature', 'Music'];

/* ================================================================
   1. Base noise, generated sample by sample
   ================================================================ */

function whiteNoise(n) {
  const out = new Float32Array(n);
  for (let i = 0; i < n; i++) out[i] = Math.random() * 2 - 1;
  return out;
}

// Paul Kellet's economical pink-noise filter.
function pinkNoise(n) {
  const out = new Float32Array(n);
  let b0 = 0, b1 = 0, b2 = 0, b3 = 0, b4 = 0, b5 = 0, b6 = 0;
  for (let i = 0; i < n; i++) {
    const w = Math.random() * 2 - 1;
    b0 = 0.99886 * b0 + w * 0.0555179;
    b1 = 0.99332 * b1 + w * 0.0750759;
    b2 = 0.96900 * b2 + w * 0.1538520;
    b3 = 0.86650 * b3 + w * 0.3104856;
    b4 = 0.55000 * b4 + w * 0.5329522;
    b5 = -0.7616 * b5 - w * 0.0168980;
    out[i] = (b0 + b1 + b2 + b3 + b4 + b5 + b6 + w * 0.5362) * 0.11;
    b6 = w * 0.115926;
  }
  return out;
}

// Brown noise: white noise integrated over time, with a slow leak so
// it cannot wander away from zero.
function brownNoise(n) {
  const out = new Float32Array(n);
  let last = 0;
  for (let i = 0; i < n; i++) {
    const w = Math.random() * 2 - 1;
    last = (last + 0.02 * w) / 1.02;
    out[i] = last * 3.5;
  }
  return out;
}

const BASE = { white: whiteNoise, pink: pinkNoise, brown: brownNoise };

function baseBuffer(ctx, kind, n) {
  const buf = ctx.createBuffer(2, n, SR);
  buf.copyToChannel(BASE[kind](n), 0);
  buf.copyToChannel(BASE[kind](n), 1); // independent channel = natural stereo width
  return buf;
}

/* ================================================================
   2. Short one-off sounds (raindrops, crackles, bubbles)
   ================================================================ */

function burstBuffer(ctx, { seconds, decay, kind = 'white', pitch = 0 }) {
  const n = Math.floor(seconds * SR);
  const buf = ctx.createBuffer(1, n, SR);
  const d = buf.getChannelData(0);
  const src = BASE[kind](n);
  for (let i = 0; i < n; i++) {
    const env = Math.exp(-(i / SR) * decay);
    const tone = pitch ? Math.sin((2 * Math.PI * pitch * i) / SR) : 1;
    d[i] = src[i] * env * tone;
  }
  return buf;
}

function scatter(ctx, dest, buf, count, gain, spread) {
  for (let i = 0; i < count; i++) {
    const src = ctx.createBufferSource();
    src.buffer = buf;
    src.playbackRate.value = 0.6 + Math.random() * 0.9;
    const g = ctx.createGain();
    g.gain.value = gain * (0.3 + Math.random() * 0.7);
    const pan = ctx.createStereoPanner();
    pan.pan.value = (Math.random() * 2 - 1) * 0.8;
    src.connect(g).connect(pan).connect(dest);
    src.start(Math.random() * spread);
  }
}

function lfo(ctx, rate, depth, target, offset) {
  const osc = ctx.createOscillator();
  osc.frequency.value = rate;
  const amp = ctx.createGain();
  amp.gain.value = depth;
  osc.connect(amp).connect(target);
  if (offset !== undefined) target.value = offset;
  osc.start(0);
  return osc;
}

/* ================================================================
   3. The recipes
   ================================================================ */

// `tone` is 0..1 from the slider; it moves a low-pass filter, which is
// what makes noise sound "brighter" or "duller".
const toneHz = t => 350 * Math.pow(46, Math.max(0, Math.min(1, t))); // 350 Hz .. 16 kHz

function buildGraph(ctx, id, tone) {
  const n = RENDER_SECONDS * SR;
  const out = ctx.createGain();
  out.gain.value = 1;
  out.connect(ctx.destination);

  const noise = kind => {
    const s = ctx.createBufferSource();
    s.buffer = baseBuffer(ctx, kind, n);
    s.start(0);
    return s;
  };
  const filter = (type, freq, Q = 1) => {
    const f = ctx.createBiquadFilter();
    f.type = type; f.frequency.value = freq; f.Q.value = Q;
    return f;
  };
  const gain = v => { const g = ctx.createGain(); g.gain.value = v; return g; };

  switch (id) {
    case 'white':
    case 'pink':
    case 'brown': {
      noise(id)
        .connect(filter('highpass', 45))
        .connect(filter('lowpass', toneHz(tone), 0.7))
        .connect(gain(id === 'brown' ? 0.85 : 0.42))
        .connect(out);
      break;
    }

    case 'rain': {
      // Body of the rain: mid-high hiss.
      noise('white').connect(filter('bandpass', 2100, 0.45)).connect(gain(0.34)).connect(out);
      // Distant rumble underneath.
      noise('brown').connect(filter('lowpass', 420, 0.7)).connect(gain(0.32)).connect(out);
      // Individual drops.
      scatter(ctx, out, burstBuffer(ctx, { seconds: 0.05, decay: 90 }), 150, 0.09, RENDER_SECONDS);
      break;
    }

    case 'stream': {
      const bp = filter('bandpass', 1500, 0.9);
      lfo(ctx, 0.13, 380, bp.frequency, 1500); // water moving over stones
      noise('pink').connect(bp).connect(gain(0.5)).connect(out);
      noise('white').connect(filter('highpass', 4200)).connect(gain(0.09)).connect(out);
      scatter(ctx, out, burstBuffer(ctx, { seconds: 0.09, decay: 42, pitch: 620 }), 60, 0.06, RENDER_SECONDS);
      break;
    }

    case 'ocean': {
      // One slow swell shapes both layers, so they breathe together.
      const swell = gain(0.45);
      lfo(ctx, 0.075, 0.4, swell.gain, 0.45);
      noise('brown').connect(filter('lowpass', 600, 0.6)).connect(swell).connect(out);

      const spray = gain(0.12);
      lfo(ctx, 0.075, 0.11, spray.gain, 0.12);
      noise('white').connect(filter('bandpass', 3200, 0.5)).connect(spray).connect(out);
      break;
    }

    case 'forest': {
      const lp = filter('lowpass', 1900, 0.6);
      lfo(ctx, 0.055, 700, lp.frequency, 1900);   // wind rising and falling
      const breath = gain(0.34);
      lfo(ctx, 0.041, 0.13, breath.gain, 0.34);
      noise('pink').connect(lp).connect(breath).connect(out);
      // Leaves.
      scatter(ctx, out, burstBuffer(ctx, { seconds: 0.14, decay: 26 }), 40, 0.04, RENDER_SECONDS);
      break;
    }

    case 'fire': {
      noise('brown').connect(filter('lowpass', 700, 0.6)).connect(gain(0.55)).connect(out);
      noise('white').connect(filter('bandpass', 1400, 0.4)).connect(gain(0.06)).connect(out);
      scatter(ctx, out, burstBuffer(ctx, { seconds: 0.035, decay: 150 }), 100, 0.19, RENDER_SECONDS);
      scatter(ctx, out, burstBuffer(ctx, { seconds: 0.012, decay: 400 }), 65, 0.26, RENDER_SECONDS);
      break;
    }

    default:
      noise('white').connect(gain(0.3)).connect(out);
  }
}

/* ================================================================
   4. Render -> seamless loop -> WAV
   ================================================================ */

async function renderChannels(id, tone) {
  const Ctx = window.OfflineAudioContext || window.webkitOfflineAudioContext;
  const ctx = new Ctx(2, RENDER_SECONDS * SR, SR);
  buildGraph(ctx, id, tone);
  const rendered = await ctx.startRendering();

  // Crossfade the tail back over the head so the loop point is inaudible.
  // Equal-power (sine/cosine) rather than linear, because two pieces of
  // uncorrelated noise added together would otherwise dip in loudness.
  const N = rendered.length;
  const fade = FADE_SECONDS * SR;
  const outLen = N - fade;
  const chans = [];

  for (let c = 0; c < 2; c++) {
    const src = rendered.getChannelData(c);
    const dst = new Float32Array(outLen);
    dst.set(src.subarray(0, outLen));
    for (let i = 0; i < fade; i++) {
      const t = i / fade;
      dst[i] = src[i] * Math.sin(t * Math.PI / 2) + src[outLen + i] * Math.cos(t * Math.PI / 2);
    }
    chans.push(dst);
  }
  normaliseLoudness(chans);
  return chans;
}

/* ---------- loudness matching ----------------------------------
   Every sound in the study has to be equally loud, or a result like
   "people concentrate better with white noise than with forest" can
   never be separated from "white noise was simply louder". Measured
   before this was added, the eight generated sounds spanned 9 LU --
   white noise sounded about twice as loud as forest.

   Perceived loudness is not the same as raw signal level: the ear is
   much more sensitive around 2-4 kHz than at the extremes, which is
   why deep brown noise measures far louder than it sounds. So the
   measurement below is K-weighted, following ITU-R BS.1770 -- the
   same standard broadcasters use -- rather than plain RMS.

   Doing it here, at render time, rather than with fixed numbers per
   sound, means the tone slider is handled too: white noise stays at
   the same loudness whether it is set bright or dark.
   --------------------------------------------------------------- */

const TARGET_LUFS = -18;    // the music tracks are encoded to this too
const PEAK_CEILING = 0.891; // -1 dBFS, so nothing ever clips

// One biquad, applied forwards over a channel.
function biquad(data, b0, b1, b2, a1, a2) {
  let x1 = 0, x2 = 0, y1 = 0, y2 = 0;
  for (let i = 0; i < data.length; i++) {
    const x0 = data[i];
    const y0 = b0 * x0 + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2;
    x2 = x1; x1 = x0; y2 = y1; y1 = y0;
    data[i] = y0;
  }
}

// BS.1770 stage 1: high shelf, +4 dB above ~1.68 kHz (head/torso effect).
function highShelf(data, f0, gainDb, Q) {
  const A = Math.pow(10, gainDb / 40);
  const w = 2 * Math.PI * f0 / SR, cw = Math.cos(w);
  const alpha = Math.sin(w) / (2 * Q), sq = 2 * Math.sqrt(A) * alpha;
  const a0 = (A + 1) - (A - 1) * cw + sq;
  biquad(data,
    A * ((A + 1) + (A - 1) * cw + sq) / a0,
    -2 * A * ((A - 1) + (A + 1) * cw) / a0,
    A * ((A + 1) + (A - 1) * cw - sq) / a0,
    2 * ((A - 1) - (A + 1) * cw) / a0,
    ((A + 1) - (A - 1) * cw - sq) / a0);
}

// BS.1770 stage 2: high pass at ~38 Hz, discarding rumble the ear barely hears.
function highPass(data, f0, Q) {
  const w = 2 * Math.PI * f0 / SR, cw = Math.cos(w);
  const alpha = Math.sin(w) / (2 * Q), a0 = 1 + alpha;
  biquad(data,
    (1 + cw) / 2 / a0, -(1 + cw) / a0, (1 + cw) / 2 / a0,
    -2 * cw / a0, (1 - alpha) / a0);
}

/** Measured loudness of a rendered stereo pair, in LUFS.
 *
 *  Uses the gated integration BS.1770 specifies: the signal is cut into
 *  overlapping 400 ms blocks and the quiet ones are dropped before
 *  averaging. That matters more than it sounds. Ocean and Forest have
 *  real lulls between waves and gusts; averaging those lulls in makes
 *  the sound measure quieter than it is, and normalising on that
 *  measurement then pushes it about 1.5 dB too loud. The steady sounds
 *  give the same answer either way.
 */
export function measureLoudness(chans) {
  const filtered = chans.map(ch => {
    const copy = Float32Array.from(ch);     // filter a copy, not the audio
    highShelf(copy, 1681.97, 3.999, 0.7071);
    highPass(copy, 38.13, 0.5003);
    return copy;
  });

  const block = Math.round(0.4 * SR);       // 400 ms
  const hop = Math.round(0.1 * SR);         // 75% overlap
  const len = filtered[0].length;
  if (len < block) return -Infinity;

  const power = [];                         // mean square per block
  for (let start = 0; start + block <= len; start += hop) {
    let sum = 0;
    for (const ch of filtered) {
      let ms = 0;
      for (let i = start; i < start + block; i++) ms += ch[i] * ch[i];
      sum += ms / block;                    // L and R both weighted 1.0
    }
    power.push(sum);
  }

  const loudness = p => -0.691 + 10 * Math.log10(p + 1e-12);
  const mean = list => list.reduce((s, v) => s + v, 0) / list.length;

  // Absolute gate: ignore anything below -70 LUFS (effectively silence).
  let kept = power.filter(p => loudness(p) > -70);
  if (!kept.length) return -Infinity;

  // Relative gate: ignore anything more than 10 LU below the running mean.
  const threshold = loudness(mean(kept)) - 10;
  kept = kept.filter(p => loudness(p) > threshold);
  if (!kept.length) return -Infinity;

  return loudness(mean(kept));
}

/** Scale a rendered stereo pair to TARGET_LUFS, in place. */
function normaliseLoudness(chans) {
  const measured = measureLoudness(chans);
  if (!Number.isFinite(measured)) return 1;

  let gain = Math.pow(10, (TARGET_LUFS - measured) / 20);

  // Never let the correction push a peak into clipping. Turning a sound
  // down slightly is far better than distorting it.
  let peak = 0;
  for (const ch of chans) {
    for (let i = 0; i < ch.length; i++) {
      const a = Math.abs(ch[i]);
      if (a > peak) peak = a;
    }
  }
  if (peak * gain > PEAK_CEILING) gain = PEAK_CEILING / peak;

  for (const ch of chans) {
    for (let i = 0; i < ch.length; i++) ch[i] *= gain;
  }
  return gain;
}

function encodeWav(chans, gain = 1) {
  const len = chans[0].length;
  const bytes = 44 + len * 4;               // 2 channels, 16 bit
  const view = new DataView(new ArrayBuffer(bytes));
  const str = (off, s) => { for (let i = 0; i < s.length; i++) view.setUint8(off + i, s.charCodeAt(i)); };

  str(0, 'RIFF');  view.setUint32(4, bytes - 8, true);
  str(8, 'WAVE');  str(12, 'fmt ');
  view.setUint32(16, 16, true);
  view.setUint16(20, 1, true);              // PCM
  view.setUint16(22, 2, true);              // stereo
  view.setUint32(24, SR, true);
  view.setUint32(28, SR * 4, true);
  view.setUint16(32, 4, true);
  view.setUint16(34, 16, true);
  str(36, 'data'); view.setUint32(40, len * 4, true);

  let off = 44;
  for (let i = 0; i < len; i++) {
    for (let c = 0; c < 2; c++) {
      const v = Math.max(-1, Math.min(1, chans[c][i] * gain));
      view.setInt16(off, v < 0 ? v * 0x8000 : v * 0x7FFF, true);
      off += 2;
    }
  }
  return new Blob([view], { type: 'audio/wav' });
}

/* ================================================================
   5. Player
   ================================================================ */

const rendered = new Map();   // "id:tone" -> Float32Array[2]
const urls = new Map();       // "id:tone:gain" -> object URL

let el = null;                // the <audio> element doing the work
let current = null;           // { id, tone, volume }
let volumeIsHonoured = null;  // iOS ignores audio.volume; we detect it

function audioEl() {
  if (!el) {
    el = new Audio();
    el.loop = true;
    el.preload = 'auto';
    el.setAttribute('playsinline', '');
  }
  return el;
}

const keyOf = (id, tone) => `${id}:${Math.round(tone * 100)}`;

async function urlFor(id, tone, gain) {
  const key = `${keyOf(id, tone)}:${Math.round(gain * 100)}`;
  if (urls.has(key)) return urls.get(key);

  const rk = keyOf(id, tone);
  if (!rendered.has(rk)) rendered.set(rk, await renderChannels(id, tone));

  const url = URL.createObjectURL(encodeWav(rendered.get(rk), gain));
  urls.set(key, url);
  return url;
}

// Some browsers (notably iOS Safari) silently refuse to change volume.
function detectVolumeSupport() {
  if (volumeIsHonoured !== null) return volumeIsHonoured;
  const a = audioEl();
  const before = a.volume;
  a.volume = 0.35;
  volumeIsHonoured = Math.abs(a.volume - 0.35) < 0.01;
  a.volume = before;
  return volumeIsHonoured;
}

/** Warm a sound up so pressing play is instant. */
export async function prepare(id, tone = 0.6) {
  const s = soundById(id);
  if (s.id === 'silence' || s.file) return true;
  const rk = keyOf(id, tone);
  if (!rendered.has(rk)) rendered.set(rk, await renderChannels(id, tone));
  return true;
}

/** Does this music file actually exist in the audio/ folder?
    Checked once per session and remembered, so redrawing the sound
    list doesn't fire the same request over and over. */
const fileChecks = new Map();
export function fileAvailable(sound) {
  if (!sound.file) return Promise.resolve(true);
  if (!fileChecks.has(sound.file)) {
    fileChecks.set(sound.file,
      fetch(sound.file, { method: 'HEAD' }).then(r => r.ok).catch(() => false));
  }
  return fileChecks.get(sound.file);
}

/**
 * Start a sound. Must be called from a real tap or click the first
 * time -- phones will not start audio on their own.
 */
export async function play(id, { tone = 0.6, volume = 0.7 } = {}) {
  const s = soundById(id);
  stop();
  if (s.id === 'silence') { current = { id, tone, volume }; return; }

  const a = audioEl();
  const honoured = detectVolumeSupport();

  if (s.file) {
    a.src = s.file;
    a.volume = honoured ? volume : 1;
  } else {
    a.src = await urlFor(id, tone, honoured ? 1 : volume);
    a.volume = honoured ? volume : 1;
  }

  current = { id, tone, volume };
  try { await a.play(); }
  catch (err) { console.warn('Audio blocked until the next tap:', err); throw err; }

  if ('mediaSession' in navigator) {
    navigator.mediaSession.metadata = new MediaMetadata({
      title: s.name, artist: 'Sound Advice', album: 'Study session'
    });
  }
}

export function stop() {
  if (el) { el.pause(); el.removeAttribute('src'); el.load(); }
  current = null;
}

export function isPlaying() { return !!(el && !el.paused && el.src); }
export function currentSound() { return current; }

/** Change loudness. Falls back to re-encoding where the OS blocks it. */
export async function setVolume(v) {
  if (!current) return;
  current.volume = v;
  const s = soundById(current.id);
  if (s.id === 'silence' || !el) return;

  if (detectVolumeSupport()) { el.volume = v; return; }
  if (s.file) return;                       // nothing we can do for a file on iOS

  const at = el.currentTime;
  el.src = await urlFor(current.id, current.tone, v);
  el.currentTime = at % 22;
  try { await el.play(); } catch {}
}

export async function setTone(t) {
  if (!current) return;
  current.tone = t;
  const s = soundById(current.id);
  if (s.file || s.id === 'silence' || !el) return;
  el.src = await urlFor(current.id, t, detectVolumeSupport() ? 1 : current.volume);
  try { await el.play(); } catch {}
}

/**
 * iPhones mute web audio when the physical silent switch is on, and
 * will not tell us. The only reliable check is to ask the person.
 */
export function needsSilentSwitchWarning() {
  return /iPad|iPhone|iPod/.test(navigator.userAgent) ||
         (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1);
}

/** A short tone used to confirm the person can actually hear something. */
export async function testBeep() {
  const Ctx = window.AudioContext || window.webkitAudioContext;
  const ctx = new Ctx();
  if (ctx.state === 'suspended') await ctx.resume();
  const osc = ctx.createOscillator();
  const g = ctx.createGain();
  osc.frequency.value = 440;
  g.gain.setValueAtTime(0.0001, ctx.currentTime);
  g.gain.exponentialRampToValueAtTime(0.22, ctx.currentTime + 0.05);
  g.gain.exponentialRampToValueAtTime(0.0001, ctx.currentTime + 0.7);
  osc.connect(g).connect(ctx.destination);
  osc.start();
  osc.stop(ctx.currentTime + 0.75);
  setTimeout(() => ctx.close(), 1000);
}
